name: Build Windows .exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build the .exe
      run: |
        pyinstaller --noconsole --onefile --add-data "audio\\sound.mp3;audio" app.py

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: RandomAudioPlayer
        path: dist/app.exe
